name: agrotrace_front
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  simple_icons: ^14.6.1
  font_awesome_flutter: ^10.7.0
  
  # Armazenamento local
  shared_preferences: ^2.2.2
  
  # Firebase (apenas para autenticação)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  
  # HTTP para requisições API
  http: ^1.1.0
  
  # QR Code Scanner
  mobile_scanner: ^5.0.0
  
  # Mapas
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Skeleton Loading
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

